TRUNCATE TABLE PRODUCT_ITEM;

INSERT INTO PRODUCT_ITEM VALUES ('I-001','マルゲリータ',800);
INSERT INTO PRODUCT_ITEM VALUES ('I-002','バジル・トマト',900);
INSERT INTO PRODUCT_ITEM VALUES ('I-003','ナス・ミートソース',1000);
INSERT INTO PRODUCT_ITEM VALUES ('I-004','アンチョビ・シーフード',1000);
INSERT INTO PRODUCT_ITEM VALUES ('I-005','チーズ・ミルフィーユ',1300);
