/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'masakura' at '16/11/01 0:32' with Gradle 2.14.1
 *
 * @author masakura, @date 16/11/01 0:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
